name: Release
run-name: Release

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  release:
    if: ${{ github.repository_owner == 'mumincelal' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Setup pnpm
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: 'pnpm'

      - name: Install dependencies
        run: npm install

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
          OVSX_PAT: ${{ secrets.OVSX_MARKETPLACE_TOKEN }}
